<a href="https://colab.research.google.com/github/digogc/Python-para-Data-Science/blob/main/Utilizando_Pandas/Diferentes_tipos_de_Arquivos/Desafios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importando o Pandas
import pandas as pd

# Salvando a URL
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv'

In [ ]:
# Lendo o arquivo
# Separador é a vírgula
# O enconding é ISO-8859-1
# As primeiras 3 linhas devem ser desconsideradas
# As últimas 9 linhas devem ser desconsideradas
# Quando as últimas linhas são separadas, é necessário selecionar a engine (Python)
dados_sus = pd.read_csv(url, sep=';', encoding='ISO-8859-1', skiprows=3, skipfooter=9, engine='python')
dados_sus

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

## Desafio Utilizando API

In [ ]:
# importando as bibliotecas necessárias
import requests
import json

In [ ]:
# realizando a requisição
dados_usuarios = requests.get('https://jsonplaceholder.typicode.com/users')
resultado = json.loads(dados_usuarios.text)

In [ ]:
# transformando em um df
dados_usuarios_normalizado = pd.json_normalize(resultado, sep='_')

In [ ]:
# visualizando o df
dados_usuarios_normalizado

,id,name,username,email,phone,website,address_street,address_suite,address_city,address_zipcode,address_geo_lat,address_geo_lng,company_name,company_catchPhrase,company_bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

# Desafio Extraindo tabela da Wikipedia

Primeiro é necessário realizar o upload do arquivo no colab

In [ ]:
# lendo o arquivo
dados_html = pd.read_html('/content/populacoes.html')

# visualizando a lista de tabelas
dados_html

[     Unnamed: 0 Posição    País (ou território dependente) Estimativa da ONU  \
 0           NaN       1                              Índia     1 429 921 746
 1           NaN       2                              China     1 426 391 281
 2           NaN       3                     Estados Unidos       346 353 341
 3           NaN       4                          Indonésia       277 184 719
 4           NaN       5                          Paquistão       240 215 932
 ..          ...     ...                                ...               ...
 245         NaN       –     Ilha de Ascensão (Reino Unido)             1 100
 246         NaN     195                           Vaticano               879
 247         NaN       –  Ilhas Cocos (Keeling) (Austrália)               605
 248         NaN       –     Tristão da Cunha (Reino Unido)               264
 249         NaN       –       Ilhas Pitcairn (Reino Unido)                67

     Crescimento desde a última estimativa      Estimativa Oficial
 0                            +269.108.746      Estimativa oficial
 1                             +87.778.313           Censo oficial
 2                             +31.241.565           Censo oficial
 3                             +33.168.546      Estimativa oficial
 4                             +65.636.932      Estimativa oficial
 ..                                    ...                     ...
 245                                   NaN  Estimativa oficial[10]
 246                                   NaN      Estimativa oficial
 247                                   NaN      Estimativa oficial
 248                                   NaN  Estimativa oficial[11]
 249                                   NaN      Estimativa oficial

 [250 rows x 6 columns],
    vdeListas de países                              vdeListas de países.1
 0             Ambiente  Bem-estar sustentável Desempenho ambiental Emi...
 1              Códigos  COI FIFA FIPS ISO Prefixo naval Telefônicos TL...
 2           Demografia  Esperança de vida Fecundidade Imigrantes Morta...
 3             Economia  Capacidade Nacional Capital Humano Competitivi...
 4              Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 5              Energia  Eletricidade Produção Renovável Gás Natural Ex...
 6                  PIB  Crescimento Real PIB Nominal per capita PIB po...
 7             Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 8           Transporte  Aeroportos Automóveis per capita Produzidos He...
 9            Geografia  Área Capital Continente Fronteiras Terrestres ...
 10         Militarismo  Armas de fogo Artilharia Batalhas Blindados de...
 11              Órgãos  BRICS Commonwealth COI CPLP Estatuto de Roma F...
 12            Política  Chefes de Estado e de Governo Constituições Co...
 13               Saúde  Antidepressivos HIV/AIDS em adultos Obesidade ...
 14            Símbolos  Emblemas Etimologia Gentílicos Grafias múltipl...
 15           Sociedade  Aborto Arranha-céus e estruturas Data de funda...,
             0                                                  1
 0     Consumo  Bebidas Cerveja Idade legal Cannabis Adultos C...
 1     Energia  Eletricidade Produção Renovável Gás Natural Ex...
 2         PIB  Crescimento Real PIB Nominal per capita PIB po...
 3    Produção  Alumínio Antimônio Bauxita Bismuto Carvão Rese...
 4  Transporte  Aeroportos Automóveis per capita Produzidos He...]

In [ ]:
# Salvando a tabela de interesse
populacoes = dados_html[0]

# Visualizando o df
populacoes

,Unnamed: 0,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Estimativa Oficial
0,NaN,1,Índia,1 429 921 746,+269.108.746,Estimativa oficial
1,NaN,2,China,1 426 391 281,+87.778.313,Censo oficial
2,NaN,3,Estados Unidos,346 353 341,+31.241.565,Censo oficial
3,NaN,4,Indonésia,277 184 719,+33.168.546,Estimativa oficial
4,NaN,5,Paquistão,240 215 932,+65.636.932,Estimativa oficial
...,...,...,...,...,...,...
245,NaN,–,Ilha de Ascensão (Reino Unido),1 100,NaN,Estimativa oficial[10]
246,NaN,195,Vaticano,879,NaN,Estimativa oficial
247,NaN,–,Ilhas Cocos (Keeling) (Austrália),605,NaN,Estimativa oficial
248,NaN,–,Tristão da Cunha (Reino Unido),264,NaN,Estimativa oficial[11]
249,NaN,–,Ilhas Pitcairn (Reino Unido),67,NaN,Estimativa oficial

In [ ]:
# Excluindo a coluna do df que não agrega informação
populacoes = populacoes.drop(columns=['Unnamed: 0'])

In [ ]:
# Visualizando novamente
populacoes

,Posição,País (ou território dependente),Estimativa da ONU,Crescimento desde a última estimativa,Estimativa Oficial
0,1,Índia,1 429 921 746,+269.108.746,Estimativa oficial
1,2,China,1 426 391 281,+87.778.313,Censo oficial
2,3,Estados Unidos,346 353 341,+31.241.565,Censo oficial
3,4,Indonésia,277 184 719,+33.168.546,Estimativa oficial
4,5,Paquistão,240 215 932,+65.636.932,Estimativa oficial
...,...,...,...,...,...
245,–,Ilha de Ascensão (Reino Unido),1 100,NaN,Estimativa oficial[10]
246,195,Vaticano,879,NaN,Estimativa oficial
247,–,Ilhas Cocos (Keeling) (Austrália),605,NaN,Estimativa oficial
248,–,Tristão da Cunha (Reino Unido),264,NaN,Estimativa oficial[11]
249,–,Ilhas Pitcairn (Reino Unido),67,NaN,Estimativa oficial

# Desafio criando um banco de dados

In [ ]:
# importando a biblioteca sqlalchemy e os métodos que serão necessários
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect

In [ ]:
# Salvando o salvando o arquivo csv como um df
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)

dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [ ]:
# Criando um banco de dados
engine = create_engine('sqlite:///:memory:')

In [ ]:
# Movendo os dados do df para o banco de dados
dados.to_sql('clientes', engine, index=False)

438463

In [ ]:
# criando um inspector para conseguir obter dados do bd
inspector = inspect(engine)

# Verificando se a tabela foi criada corretamente
print(inspector.get_columns('clientes'))

[{'name': 'ID_Cliente', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Idade', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Grau_escolaridade', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Estado_civil', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Tamanho_familia', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Categoria_de_renda', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Ocupacao', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Anos_empregado', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Rendimento_anual', 'type': FLOAT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Tem_carro', 'type': BIGINT(), 'nullable': True, 'default': None, 'primary_key': 0}, {'name': 'Moradia', 'type': TEXT(), 'nullable': True, 'default': None, 'primary_key': 0}]

In [ ]:
# Visualizando a tabela criada
query = 'SELECT * FROM clientes'

pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

## Realizando alterações no banco de dados:
1a) Alteração: \
Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

In [ ]:
# importando o método text
from sqlalchemy import text

In [ ]:
# Criando a consulta que irá realizar a atualização
query = 'UPDATE clientes SET Rendimento_anual = 300000 WHERE ID_Cliente = 6840104'

# Abrindo uma conexão com o banco de dados para realizar a consulta
with engine.connect() as conn:
  # executando a consulta
  result = conn.execute(text(query))
  # confirmando a consulta
  conn.commit()

In [ ]:
# Visualizando a linha alterada
query = 'SELECT * FROM clientes WHERE ID_Cliente = 6840104'

pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio

2a) Alteração: \
Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008809'

# Abrindo uma conexão com o banco de dados para realizar a consulta
with engine.connect() as conn:
  # executando a consulta
  result = conn.execute(text(query))
  # confirmando a consulta
  conn.commit()

query = 'SELECT * FROM clientes'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

3a) Alteração: \
Criar um novo registro de cliente seguindo as especificações abaixo: \
ID_Cliente: 6850985 \
Idade: 33 \
Grau_escolaridade: Doutorado \
Estado_civil: Solteiro \
Tamanho_familia: 1 \
Categoria_de_renda: Empregado \
Ocupacao: TI \
Anos_empregado: 2 \
Rendimento_anual: 290000 \
Tem_carro: 0 \
Moradia: Casa/apartamento próprio

In [ ]:
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'

# Abrindo uma conexão com o banco de dados para realizar a consulta
with engine.connect() as conn:
  # executando a consulta
  result = conn.execute(text(query))
  # confirmando a consulta
  conn.commit()

In [ ]:
query = 'SELECT * FROM clientes'
pd.read_sql(query, engine).tail()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
438458,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438459,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438460,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438461,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio
438462,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio